heroes/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^wolverine/$', views.Spider.as_view(),name="heroes"),
]

personajes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from heroes import views
#from posts import views as views2
from posts import urls as postsUrls
from heroes import urls as heroesUrls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(heroesUrls,namespace='wolverine')),
    #url(r'^wolverine/$', views.Spider.as_view()),
    url(r'^blog/',include(postsUrls, namespace='posts')),
    #url(r'^blog/$',views2.ListView.as_view()),
    
    #url(r'^detalle/(?P<id>\d+)/$',
    #    views2.DetailView.as_view(),
   #     name="detalle"),
    #url(r'^blog/$',views2.Blog.as_view()),
]

posts/urls.py
from django.conf.urls import url
#el punto indica importa deaquimismo
from . import views


urlpatterns = [
	url(r'^$',views.ListView.as_view(), name="blog"), #blog/
	url(r'^nuevo/$', #blog/
        views.NuevoPost.as_view(),
        name="nuevo"),
	url(r'^(?P<slug>[-\w]+)/$', #blog/
        views.DetailView.as_view(),
        name="detalle"),
#	url(r'^(?P<id>\d+)/$', #blog/
   #     views.DetailView.as_view(),
   #     name="detalle"),
]

heroes/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Post(models.Model):

	STATUS_CHOICES = (
			('draft','Draft'),
			('published','Published'),
		)

	autor = models.ForeignKey(User, related_name="blog_posts",blank=True,null=True)
	titulo = models.CharField(max_length=100,blank=True,null=True)
	cuerpo = models.TextField(blank=True,null=True)
	#fecha = models.DateTimeField(auto_now=True)
	#fecha = models.DateField(auto_now=True)
	creado = models.DateTimeField(auto_now=True,blank=True,null=True)
	actualizado = models.DateTimeField(auto_now_add=True,blank=True,null=True)
	status= models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft',blank=True,null=True)
	slug = models.SlugField(max_length=200, unique_for_date='creado',blank=True,null=True)

	class Meta:
		ordering = ('-creado',)

	def __str__(self):
		return self.titulo
 

	def get_absolute_url(self):
		return reverse('posts:detalle',args=[self.pk])

	def get_absolute_url2(self):
		return reverse('posts:detalle',args=[self.slug])

class Comentario(models.Model):
	autor = models.ForeignKey(User, related_name="comments")
	cuerpo = models.TextField()
	fecha= models.DateTimeField(auto_now=True)
	activo = models.BooleanField(default=True)
	tituloC = models.CharField(max_length=100,blank=True,null=True)
	slugC = models.CharField(max_length=200,blank=True,null=True)

	####Agregar formulario abajo de cada post 

posts/forms.py
from django import forms
from .models import Post, Comentario


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['titulo','cuerpo']

class ComentarioForm(forms.ModelForm):
	class Meta:
		model = Comentario
		fields = ['cuerpo']

heroes/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import View


# Create your views here.
class Spider(View):
	def get(self, request):
		template_name = 'home.html'
		pers = marvel()
		img = pers['data']['results'][0]['thumbnail']['path']
		#ext = pers['data']['results'][0]['thumbnail']['extension']
		#img = img + "." + ext
		img = img + '.jpg'

		context = {
		'desc':pers['data']['results'][0]['description'],
		'name':pers['data']['results'][0]['name'],
		'imgs':img,
		}

		print(context['desc'])
		return render(request,template_name,context)
		#HttpResponse()
		#return HttpResponse(desc)

def marvel():
	import requests
	import hashlib
		#sup = input('Que superheroe te interesa?')
	ts = '1'
	public_key = 'ba76cf4bfef24ead8b24d96295110d32'
	private_key = '6b310f4dc243f0f7a472a95214665c57849d872b'
	ha = hashlib.md5((ts+private_key+public_key).encode()).hexdigest()
	url = 'http://gateway.marvel.com/v1/public/'
	personaje = requests.get(
		url+'characters',
	params = {
	'apikey': public_key,
	'ts':ts,
	'hash':ha,
	'name':'hulk'
	}).json()
	description = personaje['data']['results'][0]['description']
	#print(description)
	return personaje

posts/views.py
from django.shortcuts import render
from django.views.generic import View
from .models import Post, Comentario
from django.contrib.auth.models import User
from .forms import PostForm, ComentarioForm

# Create your views here.
class ListView(View):
	
	def get(self, request):
		template_name = 'blog.html'
		user = User.objects.get(username="alucard")
		posts = user.blog_posts.all()
		
		#posts = Post.objects.filter(status='draft')
		#posts = Post.objects.all()
		context = {
			'entradas':posts
		}
		return render(request,template_name,context)


class DetailView(View):
	def get(self,request,slug):
		template_name = "detalle.html"
		form = ComentarioForm()
		post = Post.objects.get(slug=slug)
		#######
		forms = Comentario.objects.filter(slugC=slug)
		#######
		context = {
		'post':post,
		'form':form,
		'entradas':forms
		}
		return render(request,template_name,context)

	def post (self,request,slug):
		postss = Post.objects.get(slug=slug)
		forms = Comentario.objects.filter(slugC=slug)
		form = ComentarioForm()
		form = ComentarioForm(request.POST)
		post = form.save(commit=False)
		post.autor = request.user
		post.slugC = slug
		post.tituloC = postss.titulo
		post.save()
		#form.save()

		template_name = 'detalle.html'
		context ={
		'post':postss,
		'form':form,
		'entradas':forms,
		'guardado':True,
		}
		return render(request,template_name,context)


class NuevoPost(View):
	def get(self,request):
		form = PostForm()
		template_name = 'nuevo.html'
		context = {
		'form':form
		}
		return render(request,template_name,context)

	def post (self,request):
		form = PostForm(request.POST)
		post = form.save(commit=False)
		post.autor = request.user
		post.save()
		#form.save()

		template_name = 'nuevo.html'
		context ={
		'guardado':True,
		}
		return render(request,template_name,context)
#		print(request.POST.get('titulo'))
#		titulo = request.POST.get('titulo')
#		cuerpo = request.POST.get('cuerpo')
#		post = Post()
#		post.titulo = titulo
#		post.cuerpo = cuerpo
#		try:
#			post.autor = request.user
#		except:
#			pass
#		post.save()
		

#		template_name = 'nuevo.html'
#		context = {'guardado':True}
#
#		return render(request,template_name,context)
#
#class Blog(View):
#	
#	def get(self, request):
#		template_name = 'blog.html'
#		user = User.objects.get(username="alucard")
#		posts = user.blog_posts.all()
#		
#		#posts = Post.objects.filter(status='draft')
#		#posts = Post.objects.all()
#		context = {
#			'entradas':posts
#		}
#		return render(request,template_name,context)
		

heroes/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Hugo</title>
</head>
<body>
	<h2>{{name}}</h2>
  <h1>{{desc}}</h1>
  <img src="{{imgs}}">         
</body>
</html>

posts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=devicewidth">
	<title>
		{%block titulo%}
		Poké-Marvel
  		{%endblock titulo%}
	</title>
	 <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

   <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>
  <nav>
    <div class="nav-wrapper">
      <a href="{%url 'wolverine:heroes'%}" class="brand-logo">Logo</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
      </ul>
    </div>
  </nav>


  <section class="section">
  	<article class="container">
  		{%block content%}
  		{%endblock content%}
  	</article>
  </section>



 <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>	

       <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
	<script>

    $(".button-collapse").sideNav();
    </script>

</body>
</html>

posts/templates/blog.html
{%extends 'base.html'%}

{%block titulo%}
	Poké-Marvel
{%endblock titulo%}

{%block content%}
<h1>Bienvenido al blog de superheroes</h1>
	{%for entrada in entradas%}
	<a href="{{entrada.get_absolute_url2}}"><h2>{{entrada.titulo}}</h2></a>
	<!--<a href="{%url 'posts:detalle' entrada.id%}"><h2>{{entrada.titulo}}</h2></a>-->
	<p  style="text-align:justify">{{entrada.cuerpo}}</p>
	<h4>{{entrada.fecha}}</h4>
	{%empty%}
	<h2>Aún no hay posts! :(</h2>
	{%endfor%}
{%endblock content%}

posts/templates/detalle.html
{%extends 'base.html'%}

{%block titulo%}
	Detalle
{%endblock titulo%}

{%block content%}
	<h1>{{post.titulo}}</h1>
	<p style="text-align:justify">{{post.cuerpo}}</p>
	<span>{{post.creado}}</span>

	<a href="{%url 'posts:blog'%}">Volver atras</a>

	<br>
	<br>
	<br>

	<h3>Comentarios</h3>

	{%for entrada in entradas%}
	<h5>{{entrada.autor}}</h5>
	
	<p  style="text-align:justify">{{entrada.cuerpo}}</p>
	<h6>{{entrada.fecha}}</h6>
	<br><br>
	{%empty%}
	<h7>Aún no hay comentarios :(</h7>
	{%endfor%}
	
	<br>

	<form action="." method="post">
		{%csrf_token%}
		{{form.as_p}}
		<!--<input type="text" name="titulo" placeholder="Escribe el titulo del post">
		<textarea name="cuerpo" placeholder="Escribe inspirate"></textarea> -->
		<input type="submit" value="Comentar">
	</form>

{%endblock content%}

posts/templates/nuevo.html
{%extends 'base.html'%}
{%block content%}

{%if guardado%}

<h1>Tu post ha sido guardado</h1>

{%else%}

<form action="." method="post">
{%csrf_token%}
{{form.as_p}}
	<!--<input type="text" name="titulo" placeholder="Escribe el titulo del post">
	<textarea name="cuerpo" placeholder="Escribe inspirate"></textarea> -->
	<input type="submit" value="Publicar">
</form>


{%endif%}
{%endblock content%}